version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /checkout
      - /release
      - /setup-node
      - /setup-npm
    schedule:
      interval: cron
      cronjob: 0 0 * * *
      timezone: UTC
    open-pull-requests-limit: 5
