name: Setup npm Action
description: Setup npm action

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        npm install -g npm@latest

        cat << EOF >> ~/.npmrc
        //registry.npmjs.org/:_authToken = \${NPM_TOKEN_NPMJS}
        //npm.pkg.github.com/:_authToken = \${NPM_TOKEN_GITHUB}
        EOF

        if [[ -z "${NPM_TOKEN_GITHUB:-}" && -n "${GITHUB_TOKEN:-}" ]]; then
          echo "NPM_TOKEN_GITHUB=\$GITHUB_TOKEN" >> $GITHUB_ENV
        fi
