name: Publish Action
description: Publish action

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org

    - name: Update npm
      run: npm install -g npm@latest

    - run: npm install -g @softvisio/cli

    - run: softvisio-cli --version
