name: Publish Action
description: Publish action

runs:
  using: composite

  steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - shell: bash
      run: |
        npm install -g npm@latest
        npm install -g @softvisio/cli
        softvisio-cli package publish
