name: Release Action
description: Release action

runs:
  using: composite

  steps:
    - uses: softvisio/actions/checkout@v1.0.15

    - uses: softvisio/actions/setup-node@v1.0.15

    - shell: bash
      run: |
        npm install -g @corejslib/cli
        ccli package publish --yes
