name: Release Action
description: Release action

runs:
  using: composite

  steps:
    - uses: softvisio/actions/checkout@latest

    - uses: softvisio/actions/setup-node@latest

    - shell: bash
      run: |
        npm install -g @softvisio/cli
        softvisio-cli package publish --yes
